#!/bin/bash

size_start=$(du -sh $1)

#Überreste vom Mac beseitigen
rm -rf $1/.DS_Store

#Dateinamen anhand des Änderungsdatums mit einem Präfix (3-stellige Zahl) versehen, dadurch kommen die Files in die chronologisch richtige Reihenfolge
count=1
if [ $2 -eq "-t" ]; then 
    ls -tr $1 | while read file; do
        source_file="$1/$file"
        if [ $count -lt 10 ]; then
              mv -v $source_file $1'/00'$count'_'$file
        elif [ $count -lt 100 ]; then
             mv -v $source_file $1'/0'$count'_'$file
        else
             mv -v $source_file $1'/'$count'_'$file
        fi
        count=$(($count+1))
    done
else
    ls $1 | while read file; do
        source_file="$1/$file"
        if [ $count -lt 10 ]; then
              mv -v $source_file $1'/00'$count'_'$file
        elif [ $count -lt 100 ]; then
             mv -v $source_file $1'/0'$count'_'$file
        else
             mv -v $source_file $1'/'$count'_'$file
        fi
        count=$(($count+1))
    done
fi

mkdir $1/thumbnails
echo "---FOTOS---"
for f in $1/*.[JjPpGg][PpNnIi][GgFf]; 
do
	echo "$f"
	filename=$(basename $f)
	convert $f -auto-orient -thumbnail 300x300 -strip $1/thumbnails/$filename
	mogrify -resize '1300x1300>' $f
done
echo "---VIDEOS---"
for f in $1/*.[mM][PpoO][4vV];
do
        echo "$f"
        filename=$(basename $f)
	mv $f $f.0

#	man hat 2 Optionen: entweder alle Videos drehen oder nicht, es kann durch aus/einkommentieren der folgenden Zeilen gesteuert werden:

#	folgende Zeile Dreht alle Videos um 180 Grad - evtl nicht immer erwünscht
#	avconv -y -i $f.0 -movflags faststart -strict experimental -vf "scale=960:-1,hflip,vflip" $f 
	
#	folgende Zeile dreht die Videos NICHT
	ffmpeg -y -i $f.0 -movflags faststart -strict experimental -vf "scale=960:-1" $f

#	folgende Zeile erzeugt das Vorschaubild für das Video
	ffmpeg -y -i $f -f mjpeg -vframes 1 -ss 1 $1/thumbnails/$filename.jpg
	mogrify -resize '400x400>' $1/thumbnails/$filename.jpg
done
#überreste vom Konvertieren beseitigen
rm -rf $1/*.0
ln -s ~/Documents/exchange_pictures/index.php $1/index.php

size_end=$(du -sh $1)

echo 'Size at start:'
echo $size_start

echo 'Size at end:'
echo $size_end
