#!/bin/bash

pic=$(dirname $1)/thumbnails/$(basename $1).jpg

echo "---FOTOS---"
convert -rotate 180 $pic $pic.0
mv $pic.0 $pic

echo "---VIDEOS---"
mv $1 $1.0
avconv -i $1.0 -c:a copy -vf "hflip,vflip" $1
